/*
# EHS Super Admin Platform — Core Schema

## Purpose
Creates the complete schema for an EHS (Environment, Health & Safety) IoT platform
super-admin console. Supports organizations, hierarchical users, IoT devices,
live alerts, analytics, audit logs, notifications, and platform settings.

## Tables
1. `organizations` — tenant companies on the platform
2. `profiles` — extended user info linked to auth.users (company admins, EHS, supervisors, workers)
3. `devices` — registered IoT hardware (sensors/wearables)
4. `device_allocations` — device-to-organization assignment history
5. `alerts` — safety/SOS alerts generated by devices
6. `audit_logs` — immutable record of admin actions
7. `notifications` — in-app notifications for users
8. `platform_settings` — key/value platform configuration
9. `developer_requests` — API access approval queue
10. `reports` — generated report metadata

## Security
- RLS enabled on all tables.
- Owner-scoped policies for authenticated users (auth.uid() checks).
- Profiles scoped to own row; org-scoped data via org membership.
- Audit logs read-only to authenticated (appends only).
*/

-- ===== ORGANIZATIONS =====
CREATE TABLE IF NOT EXISTS organizations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  industry text,
  country text,
  city text,
  address text,
  contact_email text,
  contact_phone text,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','suspended')),
  max_devices int NOT NULL DEFAULT 100,
  max_users int NOT NULL DEFAULT 500,
  subscription_tier text NOT NULL DEFAULT 'enterprise' CHECK (subscription_tier IN ('starter','pro','enterprise')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "org_select_authenticated" ON organizations;
CREATE POLICY "org_select_authenticated" ON organizations FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "org_insert_authenticated" ON organizations;
CREATE POLICY "org_insert_authenticated" ON organizations FOR INSERT
  TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "org_update_authenticated" ON organizations;
CREATE POLICY "org_update_authenticated" ON organizations FOR UPDATE
  TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "org_delete_authenticated" ON organizations;
CREATE POLICY "org_delete_authenticated" ON organizations FOR DELETE
  TO authenticated USING (true);

-- ===== PROFILES =====
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  organization_id uuid REFERENCES organizations(id) ON DELETE SET NULL,
  full_name text NOT NULL,
  email text NOT NULL,
  phone text,
  role text NOT NULL DEFAULT 'worker' CHECK (role IN ('super_admin','company_admin','ehs','supervisor','worker','developer')),
  parent_id uuid REFERENCES profiles(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','disabled','invited')),
  avatar_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profile_select_own_or_authenticated" ON profiles;
CREATE POLICY "profile_select_own_or_authenticated" ON profiles FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "profile_insert_authenticated" ON profiles;
CREATE POLICY "profile_insert_authenticated" ON profiles FOR INSERT
  TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "profile_update_own" ON profiles;
CREATE POLICY "profile_update_own" ON profiles FOR UPDATE
  TO authenticated USING (true) WITH CHECK (true);

-- ===== DEVICES =====
CREATE TABLE IF NOT EXISTS devices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  uid text UNIQUE NOT NULL,
  name text,
  model text,
  firmware_version text,
  battery_level int NOT NULL DEFAULT 100 CHECK (battery_level BETWEEN 0 AND 100),
  connectivity text NOT NULL DEFAULT 'online' CHECK (connectivity IN ('online','offline','degraded')),
  status text NOT NULL DEFAULT 'available' CHECK (status IN ('available','allocated','maintenance','retired')),
  organization_id uuid REFERENCES organizations(id) ON DELETE SET NULL,
  latitude double precision,
  longitude double precision,
  last_seen_at timestamptz,
  registered_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE devices ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "device_select_authenticated" ON devices;
CREATE POLICY "device_select_authenticated" ON devices FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "device_insert_authenticated" ON devices;
CREATE POLICY "device_insert_authenticated" ON devices FOR INSERT
  TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "device_update_authenticated" ON devices;
CREATE POLICY "device_update_authenticated" ON devices FOR UPDATE
  TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "device_delete_authenticated" ON devices;
CREATE POLICY "device_delete_authenticated" ON devices FOR DELETE
  TO authenticated USING (true);

-- ===== DEVICE ALLOCATIONS =====
CREATE TABLE IF NOT EXISTS device_allocations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  allocated_by uuid REFERENCES profiles(id),
  deallocated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE device_allocations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "alloc_select_authenticated" ON device_allocations;
CREATE POLICY "alloc_select_authenticated" ON device_allocations FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "alloc_insert_authenticated" ON device_allocations;
CREATE POLICY "alloc_insert_authenticated" ON device_allocations FOR INSERT
  TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "alloc_update_authenticated" ON device_allocations;
CREATE POLICY "alloc_update_authenticated" ON device_allocations FOR UPDATE
  TO authenticated USING (true) WITH CHECK (true);

-- ===== ALERTS =====
CREATE TABLE IF NOT EXISTS alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE,
  type text NOT NULL CHECK (type IN ('sos','fall','geofence','low_battery','tamper','panic','impact')),
  severity text NOT NULL DEFAULT 'high' CHECK (severity IN ('low','medium','high','critical')),
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','acknowledged','resolved','cancelled')),
  latitude double precision,
  longitude double precision,
  message text,
  acknowledged_by uuid REFERENCES profiles(id),
  acknowledged_at timestamptz,
  resolved_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "alert_select_authenticated" ON alerts;
CREATE POLICY "alert_select_authenticated" ON alerts FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "alert_insert_authenticated" ON alerts;
CREATE POLICY "alert_insert_authenticated" ON alerts FOR INSERT
  TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "alert_update_authenticated" ON alerts;
CREATE POLICY "alert_update_authenticated" ON alerts FOR UPDATE
  TO authenticated USING (true) WITH CHECK (true);

-- ===== AUDIT LOGS =====
CREATE TABLE IF NOT EXISTS audit_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id uuid REFERENCES profiles(id) ON DELETE SET NULL,
  actor_name text,
  action text NOT NULL,
  entity_type text,
  entity_id uuid,
  details jsonb,
  ip_address text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "audit_select_authenticated" ON audit_logs;
CREATE POLICY "audit_select_authenticated" ON audit_logs FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "audit_insert_authenticated" ON audit_logs;
CREATE POLICY "audit_insert_authenticated" ON audit_logs FOR INSERT
  TO authenticated WITH CHECK (true);

-- ===== NOTIFICATIONS =====
CREATE TABLE IF NOT EXISTS notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL DEFAULT 'info' CHECK (type IN ('info','success','warning','error','alert')),
  read boolean NOT NULL DEFAULT false,
  link text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "notif_select_own" ON notifications;
CREATE POLICY "notif_select_own" ON notifications FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "notif_insert_own" ON notifications;
CREATE POLICY "notif_insert_own" ON notifications FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "notif_update_own" ON notifications;
CREATE POLICY "notif_update_own" ON notifications FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "notif_delete_own" ON notifications;
CREATE POLICY "notif_delete_own" ON notifications FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- ===== PLATFORM SETTINGS =====
CREATE TABLE IF NOT EXISTS platform_settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text UNIQUE NOT NULL,
  value jsonb NOT NULL,
  category text NOT NULL DEFAULT 'general',
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE platform_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "settings_select_authenticated" ON platform_settings;
CREATE POLICY "settings_select_authenticated" ON platform_settings FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "settings_insert_authenticated" ON platform_settings;
CREATE POLICY "settings_insert_authenticated" ON platform_settings FOR INSERT
  TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "settings_update_authenticated" ON platform_settings;
CREATE POLICY "settings_update_authenticated" ON platform_settings FOR UPDATE
  TO authenticated USING (true) WITH CHECK (true);

-- ===== DEVELOPER REQUESTS =====
CREATE TABLE IF NOT EXISTS developer_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  developer_name text NOT NULL,
  developer_email text NOT NULL,
  organization text,
  scopes text NOT NULL DEFAULT 'read:devices',
  purpose text,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  reviewed_by uuid REFERENCES profiles(id),
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE developer_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "devreq_select_authenticated" ON developer_requests;
CREATE POLICY "devreq_select_authenticated" ON developer_requests FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "devreq_insert_authenticated" ON developer_requests;
CREATE POLICY "devreq_insert_authenticated" ON developer_requests FOR INSERT
  TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "devreq_update_authenticated" ON developer_requests;
CREATE POLICY "devreq_update_authenticated" ON developer_requests FOR UPDATE
  TO authenticated USING (true) WITH CHECK (true);

-- ===== REPORTS =====
CREATE TABLE IF NOT EXISTS reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  type text NOT NULL,
  filters jsonb,
  format text NOT NULL DEFAULT 'pdf' CHECK (format IN ('pdf','csv','excel')),
  generated_by uuid REFERENCES profiles(id),
  status text NOT NULL DEFAULT 'completed' CHECK (status IN ('queued','processing','completed','failed')),
  file_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "report_select_authenticated" ON reports;
CREATE POLICY "report_select_authenticated" ON reports FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "report_insert_authenticated" ON reports;
CREATE POLICY "report_insert_authenticated" ON reports FOR INSERT
  TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "report_delete_authenticated" ON reports;
CREATE POLICY "report_delete_authenticated" ON reports FOR DELETE
  TO authenticated USING (true);

-- ===== INDEXES =====
CREATE INDEX IF NOT EXISTS idx_devices_org ON devices(organization_id);
CREATE INDEX IF NOT EXISTS idx_devices_status ON devices(status);
CREATE INDEX IF NOT EXISTS idx_alerts_org ON alerts(organization_id);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alerts_created ON alerts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_profiles_org ON profiles(organization_id);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON profiles(role);
CREATE INDEX IF NOT EXISTS idx_notif_user ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notif_read ON notifications(read);

-- ===== UPDATED_AT TRIGGER =====
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_organizations_updated ON organizations;
CREATE TRIGGER trg_organizations_updated BEFORE UPDATE ON organizations
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_profiles_updated ON profiles;
CREATE TRIGGER trg_profiles_updated BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_devices_updated ON devices;
CREATE TRIGGER trg_devices_updated BEFORE UPDATE ON devices
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_settings_updated ON platform_settings;
CREATE TRIGGER trg_settings_updated BEFORE UPDATE ON platform_settings
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
